#!/bin/sh

echo "copying environmental variables"

#TODO: check if all the necessary programs actually exist... warn if not!

cp zshrc ~/.zshrc
cp tmux.conf ~/.tmux.conf
cp gitconfig ~/.gitconfig
cp bashrc ~/.bashrc

echo "changing shell to ZSH"
chsh -s $(which zsh)

echo "adding vimrc for root, you better be in WHEEL!"
sudo cp vimrc /root/.vimrc
